### ISSUE TITLE
Can I use it directly to evaluate the coherence between the response and the history utterances?

### ISSUE THREAD

**Issue by gm0616** [nouhadziri/DialogEntailment#1]
After installing the DialogEntailment package, how can I use it to score a certain response given the conversation history in Python? Can you give me a simple demo?

Thank you very much!

**Comment by ehsk** [comment]
You can use the [SemanticSimilarity](https://github.com/nouhadziri/DialogEntailment/blob/92a0b661447accab3bcc766123170f69a08c8205/dialogentail/semantic_similarity.py) metric to score a given response as follows:

```python
from dialogentail.semantic_similarity import SemanticSimilarity

ss = SemanticSimilarity()
sim_ground_truth, sim_generated_resp = ss.compute_metric(
    conversation_history=["hello , would you like to go to a concert ?", "sure ! what kind of concert ?"],
    actual_response="i think i'll ponder that for a while .", 
    generated_response="i like jazz .")
```

The output `sim_ground_truth` indicates the semantic similarity measure for the actual response and the output `sim_generated_resp` measures the metric for the generated response. Both are dictionaries with the below structure:
```
{
  'i': 0, 'gen_type': 'unknown', 
  'SS_context': 0.6179008483886719,
  'delta_SS_context': -0.018185973167419434, 
  'SS_Utt_-1': 0.524748682975769, 'delta_SS_Utt_-1': -0.0657694935798645,
  'SS_Utt_-2': 0.5820484161376953, 'delta_SS_Utt_-2': -0.034501492977142334
}
```
where `SS_context` refers to the similarity between a response and the whole conversation history, `SS_Utt_-1` refers to the similarity between a response and the most recent utterance in the conversation (e.g., "sure ! what kind of concert ?" in the example), and `SS_Utt_-2` refers to the similarity between a response and the second most recent utterance in the history. The keys starting with `delta` are the similarity difference between the actual response and the generated response.

Note that in the example, the messages are tokenized. If the input is not tokenized, `tokenized=False` must be passed to the `compute_metric` function.

The default embedding used to compute similarity is Elmo. To use BERT, the code should change like this:
```python
ss = SemanticSimilarity(embedding_method='bert')
```

The supported embedding methods are provided [here](https://github.com/nouhadziri/DialogEntailment/blob/92a0b661447accab3bcc766123170f69a08c8205/dialogentail/embedder/factory.py).

For an input response file, we implemented `compute_metric_for_file`:
```python
similarities = ss.compute_metric_for_file('responses.txt', generator_types=["Method1", "Method2"])
```
The file format is explained [here](https://github.com/nouhadziri/DialogEntailment/tree/92a0b661447accab3bcc766123170f69a08c8205#custom-test-data).

Hope this helps!
