### ISSUE TITLE
How to obtain the results of Table 2 in the paper?

### ISSUE THREAD

**Issue by ChineseYjh** [nouhadziri/DialogEntailment#2]
### How to obtain the results of Table 2 in the paper?
ESIM+ELMo and BERT both output labels like **entailment, contradiction or neutral**. But in Reddit and OpenSubtitles majority vote of the 4-scale human rating constitutes the labels(**Excellent, good, poor, bad**). How to calculate accuracy in this situation?
Thank you very much!

**Comment by ehsk** [comment]
The results reported in Table 2 refer to the accuracy of the inference models on the InferConvAI dataset, a synthetic inference dataset built upon the conversational data (see section 4 for more details). Therefore, the labels in the InferConvAI dataset are _entailment_, _contradiction_, and _neutral_. The box plot in Figure 1 shows the correlation of inference predictions with human judgment.

**Comment by ChineseYjh** [comment]
The following paragraph is extracted from section 5.1 in your paper. It looks like the evaluation is conducted in Reddit and OpenSubtitles. And in Table 2 there are **two columns**, one of which is for **Reddit** and another is for **OpenSubtitles**. If evaluation is conducted in InferConvAI, why the evaluation results are shown in two columns? I don't quite understand the meaning of this table. Thank you very much!

> We pick two state-of-the-art NLI models (i.e., ESIM (Chen et al., 2016) and BERT (Devlin
et al., 2018)). These models were trained on the InferConvAI dataset. During evaluation, we use
our test dialogue corpus from Reddit and OpenSubtitles, in which the majority vote of the 4-scale
human rating constitutes the labels. The results are illustrated in Table 2.

**Comment by ehsk** [comment]
Sorry, you are absolutely right. We took a majority vote of human scores and then determine the label. More precisely, [here](https://github.com/nouhadziri/DialogEntailment/blob/92a0b661447accab3bcc766123170f69a08c8205/dialogentail/preprocessing/responses_to_nli.py#L7) is how we mapped the human judgment scores into the inference labels.

**Comment by ChineseYjh** [comment]
Thanks for your explanation~
