### ISSUE TITLE
Test script

### ISSUE THREAD

**Issue by directv00** [nouhadziri/DialogEntailment#3]
Can you guide me how to test after training cause it described a little vaguely.
Please show a test script you've made.
Thanks,

**Comment by ehsk** [comment]
If you trained a BERT model, the evaluation command can be used for testing:
```
python -m dialogentail.huggingface --do_eval --eval_dataset /path/to/test_data --model /path/to/model
```

For ESIM, the test command should be:
```
allennlp evaluate -c /path/to/eval_config -s /path/to/out_file
```

It's been a long time since we worked on this repo, so if these commands fail, please let us know, we can take a closer look later on.
