### ISSUE TITLE
How to test with other metrics ?

### ISSUE THREAD

**Issue by wizare** [nouhadziri/DialogEntailment#4]
Hi. I have already trained my BERT model and tested my responses with the entailment model. 

But I didn't know how to test with other metrics, i.e., ``Semantic Similarity``, ``Word-level metrics``, ``Consistency by textual entailment``.

Can you show a script as an example?
Thanks

**Comment by ehsk** [comment]
Sorry for the late reply! This somehow slipped my mind.

If it still helps, you can find semantic similarity and consistency metrics in our repo: [here](https://github.com/nouhadziri/DialogEntailment/blob/master/dialogentail/semantic_similarity.py) and [here](https://github.com/nouhadziri/DialogEntailment/blob/master/dialogentail/coherence.py). For both metrics, we implemented two methods: `compute_metric` (for one sample) and `compute_metric_for_file` (for an entire file).

For word-overlap metrics, you can use [this](https://github.com/Maluuba/nlg-eval) repo.

Hope this helps!
