### ISSUE TITLE
Where can I find the original dataset

### ISSUE THREAD

**Issue by pengshancai** [nouhadziri/DialogEntailment#5]
Dear author, 
I am impressed by the work! I have a few questions though.
1. It seems the proposed dataset is built upon a previous dataset called ConvAI. Is this dataset also named PERSONA-CHAT Dataset? In addition, where can I download this original dataset? i.e. the convai_file in convai_to_nli.py?
2. As I observed from the proposed dataset, each dialogue only has one turn. I wonder if you have tried multi-turn dialogue? If so, how is the performance?
Thanks!

**Comment by ehsk** [comment]
Thanks for your interest in our work!

1. ConvAI and Persona-Chat are different datasets but they have similar structures. You can access both datasets via ParlAI ([here](https://github.com/facebookresearch/ParlAI/tree/master/projects/convai2) for ConvAI and [here](https://github.com/facebookresearch/ParlAI/tree/master/projects/personachat) for Persona-Chat).
2. You're correct. We tested on single utterances as history. I don't think we tested with multi-turn dialogues.

Hope this helps!

**Comment by pengshancai** [comment]
Thanks! Your responses are helpful!

**Comment by pengshancai** [comment]
Dear authors,
I have downloaded the ConvAI dataset, however, I found there are multiple txt files. e.g. 

train_both_original_no_cands.txt
train_both_revised_no_cands.txt
train_none_original_no_cands.txt
train_other_original_no_cands.txt
train_other_revised_no_cands.txt
train_self_original_no_cands.txt
train_self_revised_no_cands.txt


Could you please let me know which one did you use the generate your InferConvAI dataset?
Thanks!

**Comment by ehsk** [comment]
I think we have used the "both_revised_no_cands" data.
