### ISSUE TITLE
could you please release the already trained model

### ISSUE THREAD

**Issue by Tylerjoe** [nouhadziri/DialogEntailment#8]
Thanks for your great work, and I am impressed by the work! 
could you please release the trained model for a test 

Thanks

**Comment by ehsk** [comment]
Thanks for your interest in our work!

This work was done a few years ago. Unfortunately, we don't have access to our trained models anymore. You may train your own model by following the steps [here](https://github.com/nouhadziri/DialogEntailment#train-an-entailment-model).
